# Example workflow
# .github/workflows/example.yml

name: 'oidc'
on:
  push:
    branches:
    - 'main'
jobs:
  run:
    name: 'example tf run'
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }} # this is the output provider_name from the TF module
        service_account: ${{ secrets.SA_EMAIL }} # this is a SA email configured using the TF module with access to YOUR-GCS-BUCKET
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false
    - name: Terraform debug
      id: debug
      run: |
        tree $GITHUB_WORKSPACE
        ls -l $GITHUB_WORKSPACE
      shell: bash
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform/github-runners # Use your environment folder
      shell: bash
    - name: Terraform Plan
      id: plan
      run: |
        echo "${{ secrets.TFVARS }}" > terraform.tfvars
        terraform plan -input=false -no-color -out tf.plan
      working-directory: terraform/github-runners # Use your environment folder
      shell: bash